[project]
name = "extract-invoice-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.36.8",
    "requests>=2.32.3",
    "typer>=0.15.1",
]

